import { HttpSession } from '../src/internal/http.js';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36';
const html = (await new HttpSession().request('GET', 'https://x.com', { headers: { 'User-Agent': UA } })).text;
const inline = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map((m) => m[1]).join('\n');
console.log('logged-out page:', html.length, 'bytes | inline scripts:', inline.length, 'bytes');
console.log('  has ondemand.s in manifest:', inline.includes('"ondemand.s"'));
console.log('  has .u= builder:', /\.u\s*=\s*\w*\s*=>/.test(inline));
console.log('  16-hex hash pairs:', [...inline.matchAll(/(\d{3,7}):"([0-9a-f]{16})"/g)].length);
console.log('  site-verification:', /twitter-site-verification/.test(html));
console.log('  loading-x-anim frames:', (html.match(/loading-x-anim/g) || []).length);
console.log('  legacy inline literal:', /['"]ondemand\.s['"]\s*:\s*['"][\w]*['"]/.test(html));
