/** GraphQL endpoints, ported verbatim from twikit/client/gql.py */

import { DOMAIN } from '../constants.js';

const url = (path: string): string => `https://${DOMAIN}/i/api/graphql/${path}`;

export const Endpoint = {
  SEARCH_TIMELINE: url('flaR-PUMshxFWZWPNpq4zA/SearchTimeline'),
  SIMILAR_POSTS: url('EToazR74i0rJyZYalfVEAQ/SimilarPosts'),
  CREATE_NOTE_TWEET: url('iCUB42lIfXf9qPKctjE5rQ/CreateNoteTweet'),
  CREATE_TWEET: url('SiM_cAu83R0wnrpmKQQSEw/CreateTweet'),
  CREATE_SCHEDULED_TWEET: url('LCVzRQGxOaGnOnYH01NQXg/CreateScheduledTweet'),
  DELETE_TWEET: url('VaenaVgh5q5ih7kvyVjgtg/DeleteTweet'),
  USER_BY_SCREEN_NAME: url('NimuplG1OB7Fd2btCLdBOw/UserByScreenName'),
  USER_BY_REST_ID: url('tD8zKvQzwY3kdx5yz6YmOw/UserByRestId'),
  TWEET_DETAIL: url('U0HTv-bAWTBYylwEMT7x5A/TweetDetail'),
  TWEET_RESULT_BY_REST_ID: url('Xl5pC_lBk_gcO2ItU39DQw/TweetResultByRestId'),
  FETCH_SCHEDULED_TWEETS: url('ITtjAzvlZni2wWXwf295Qg/FetchScheduledTweets'),
  DELETE_SCHEDULED_TWEET: url('CTOVqej0JBXAZSwkp1US0g/DeleteScheduledTweet'),
  RETWEETERS: url('X-XEqG5qHQSAwmvy00xfyQ/Retweeters'),
  FAVORITERS: url('LLkw5EcVutJL6y-2gkz22A/Favoriters'),
  FETCH_COMMUNITY_NOTE: url('fKWPPj271aTM-AB9Xp48IA/BirdwatchFetchOneNote'),
  USER_TWEETS: url('QWF3SzpHmykQHsQMixG0cg/UserTweets'),
  USER_TWEETS_AND_REPLIES: url('vMkJyzx1wdmvOeeNG0n6Wg/UserTweetsAndReplies'),
  USER_MEDIA: url('2tLOJWwGuCTytDrGBg8VwQ/UserMedia'),
  USER_LIKES: url('IohM3gxQHfvWePH5E3KuNA/Likes'),
  USER_HIGHLIGHTS_TWEETS: url('tHFm_XZc_NNi-CfUThwbNw/UserHighlightsTweets'),
  HOME_TIMELINE: url('-X_hcgQzmHGl29-UXxz4sw/HomeTimeline'),
  HOME_LATEST_TIMELINE: url('U0cdisy7QFIoTfu3-Okw0A/HomeLatestTimeline'),
  FAVORITE_TWEET: url('lI07N6Otwv1PhnEgXILM7A/FavoriteTweet'),
  UNFAVORITE_TWEET: url('ZYKSe-w7KEslx3JhSIk5LA/UnfavoriteTweet'),
  CREATE_RETWEET: url('ojPdsZsimiJrUGLR1sjUtA/CreateRetweet'),
  DELETE_RETWEET: url('iQtK4dl5hBmXewYZuEOKVw/DeleteRetweet'),
  CREATE_BOOKMARK: url('aoDbu3RHznuiSkQ9aNM67Q/CreateBookmark'),
  BOOKMARK_TO_FOLDER: url('4KHZvvNbHNf07bsgnL9gWA/bookmarkTweetToFolder'),
  DELETE_BOOKMARK: url('Wlmlj2-xzyS1GN3a6cj-mQ/DeleteBookmark'),
  BOOKMARKS: url('qToeLeMs43Q8cr7tRYXmaQ/Bookmarks'),
  BOOKMARK_FOLDER_TIMELINE: url('8HoabOvl7jl9IC1Aixj-vg/BookmarkFolderTimeline'),
  BOOKMARKS_ALL_DELETE: url('skiACZKC1GDYli-M8RzEPQ/BookmarksAllDelete'),
  BOOKMARK_FOLDERS_SLICE: url('i78YDd0Tza-dV4SYs58kRg/BookmarkFoldersSlice'),
  EDIT_BOOKMARK_FOLDER: url('a6kPp1cS1Dgbsjhapz1PNw/EditBookmarkFolder'),
  DELETE_BOOKMARK_FOLDER: url('2UTTsO-6zs93XqlEUZPsSg/DeleteBookmarkFolder'),
  CREATE_BOOKMARK_FOLDER: url('6Xxqpq8TM_CREYiuof_h5w/createBookmarkFolder'),
  FOLLOWERS: url('gC_lyAxZOptAMLCJX5UhWw/Followers'),
  BLUE_VERIFIED_FOLLOWERS: url('VmIlPJNEDVQ29HfzIhV4mw/BlueVerifiedFollowers'),
  FOLLOWERS_YOU_KNOW: url('f2tbuGNjfOE8mNUO5itMew/FollowersYouKnow'),
  FOLLOWING: url('2vUj-_Ek-UmBVDNtd8OnQA/Following'),
  USER_CREATOR_SUBSCRIPTIONS: url('Wsm5ZTCYtg2eH7mXAXPIgw/UserCreatorSubscriptions'),
  USER_DM_REACTION_MUTATION_ADD_MUTATION: url('VyDyV9pC2oZEj6g52hgnhA/useDMReactionMutationAddMutation'),
  USER_DM_REACTION_MUTATION_REMOVE_MUTATION: url('bV_Nim3RYHsaJwMkTXJ6ew/useDMReactionMutationRemoveMutation'),
  DM_MESSAGE_DELETE_MUTATION: url('BJ6DtxA2llfjnRoRjaiIiw/DMMessageDeleteMutation'),
  ADD_PARTICIPANTS_MUTATION: url('oBwyQ0_xVbAQ8FAyG0pCRA/AddParticipantsMutation'),
  CREATE_LIST: url('EYg7JZU3A1eJ-wr2eygPHQ/CreateList'),
  EDIT_LIST_BANNER: url('t_DsROHldculsB0B9BUAWw/EditListBanner'),
  DELETE_LIST_BANNER: url('Y90WuxdWugtMRJhkXTdvzg/DeleteListBanner'),
  UPDATE_LIST: url('dIEI1sbSAuZlxhE0ggrezA/UpdateList'),
  LIST_ADD_MEMBER: url('lLNsL7mW6gSEQG6rXP7TNw/ListAddMember'),
  LIST_REMOVE_MEMBER: url('cvDFkG5WjcXV0Qw5nfe1qQ/ListRemoveMember'),
  LIST_MANAGEMENT_PACE_TIMELINE: url('47170qwZCt5aFo9cBwFoNA/ListsManagementPageTimeline'),
  LIST_BY_REST_ID: url('9hbYpeVBMq8-yB8slayGWQ/ListByRestId'),
  LIST_LATEST_TWEETS_TIMELINE: url('HjsWc-nwwHKYwHenbHm-tw/ListLatestTweetsTimeline'),
  LIST_MEMBERS: url('BQp2IEYkgxuSxqbTAr1e1g/ListMembers'),
  LIST_SUBSCRIBERS: url('74wGEkaBxrdoXakWTWMxRQ/ListSubscribers'),
  SEARCH_COMMUNITY: url('daVUkhfHn7-Z8llpYVKJSw/CommunitiesSearchQuery'),
  COMMUNITY_QUERY: url('lUBKrilodgg9Nikaw3cIiA/CommunityQuery'),
  COMMUNITY_MEDIA_TIMELINE: url('Ht5K2ckaZYAOuRFmFfbHig/CommunityMediaTimeline'),
  COMMUNITY_TWEETS_TIMELINE: url('mhwSsmub4JZgHcs0dtsjrw/CommunityTweetsTimeline'),
  COMMUNITIES_MAIN_PAGE_TIMELINE: url('4-4iuIdaLPpmxKnA3mr2LA/CommunitiesMainPageTimeline'),
  JOIN_COMMUNITY: url('xZQLbDwbI585YTG0QIpokw/JoinCommunity'),
  LEAVE_COMMUNITY: url('OoS6Kd4-noNLXPZYHtygeA/LeaveCommunity'),
  REQUEST_TO_JOIN_COMMUNITY: url('XwWChphD_6g7JnsFus2f2Q/RequestToJoinCommunity'),
  MEMBERS_SLICE_TIMELINE_QUERY: url('KDAssJ5lafCy-asH4wm1dw/membersSliceTimeline_Query'),
  MODERATORS_SLICE_TIMELINE_QUERY: url('9KI_r8e-tgp3--N5SZYVjg/moderatorsSliceTimeline_Query'),
  COMMUNITY_TWEET_SEARCH_MODULE_QUERY: url('5341rmzzvdjqfmPKfoHUBw/CommunityTweetSearchModuleQuery'),
  TWEET_RESULTS_BY_REST_IDS: url('PTN9HhBAlpoCTHfspDgqLA/TweetResultsByRestIds'),
} as const;
