/** v1.1 / internal endpoints, ported verbatim from twikit/client/v11.py */

import { DOMAIN } from '../constants.js';

export const V11Endpoint = {
  GUEST_ACTIVATE: `https://api.${DOMAIN}/1.1/guest/activate.json`,
  ONBOARDING_SSO_INIT: `https://api.${DOMAIN}/1.1/onboarding/sso_init.json`,
  ACCOUNT_LOGOUT: `https://api.${DOMAIN}/1.1/account/logout.json`,
  ONBOARDING_TASK: `https://api.${DOMAIN}/1.1/onboarding/task.json`,
  SETTINGS: `https://api.${DOMAIN}/1.1/account/settings.json`,
  UPLOAD_MEDIA: `https://upload.${DOMAIN}/i/media/upload.json`,
  UPLOAD_MEDIA_2: `https://upload.${DOMAIN}/i/media/upload2.json`,
  CREATE_MEDIA_METADATA: `https://api.${DOMAIN}/1.1/media/metadata/create.json`,
  CREATE_CARD: `https://caps.${DOMAIN}/v2/cards/create.json`,
  VOTE: `https://caps.${DOMAIN}/v2/capi/passthrough/1`,
  REVERSE_GEOCODE: `https://api.${DOMAIN}/1.1/geo/reverse_geocode.json`,
  SEARCH_GEO: `https://api.${DOMAIN}/1.1/geo/search.json`,
  GET_PLACE: (id: string | number): string => `https://api.${DOMAIN}/1.1/geo/id/${id}.json`,
  CREATE_FRIENDSHIPS: `https://${DOMAIN}/i/api/1.1/friendships/create.json`,
  DESTROY_FRIENDSHIPS: `https://${DOMAIN}/i/api/1.1/friendships/destroy.json`,
  CREATE_BLOCKS: `https://${DOMAIN}/i/api/1.1/blocks/create.json`,
  DESTROY_BLOCKS: `https://${DOMAIN}/i/api/1.1/blocks/destroy.json`,
  CREATE_MUTES: `https://${DOMAIN}/i/api/1.1/mutes/users/create.json`,
  DESTROY_MUTES: `https://${DOMAIN}/i/api/1.1/mutes/users/destroy.json`,
  GUIDE: `https://${DOMAIN}/i/api/2/guide.json`,
  AVAILABLE_TRENDS: `https://api.${DOMAIN}/1.1/trends/available.json`,
  PLACE_TRENDS: `https://api.${DOMAIN}/1.1/trends/place.json`,
  FOLLOWERS_LIST: `https://api.${DOMAIN}/1.1/followers/list.json`,
  FRIENDS_LIST: `https://api.${DOMAIN}/1.1/friends/list.json`,
  FOLLOWERS_IDS: `https://api.${DOMAIN}/1.1/followers/ids.json`,
  FRIENDS_IDS: `https://api.${DOMAIN}/1.1/friends/ids.json`,
  DM_NEW: `https://${DOMAIN}/i/api/1.1/dm/new2.json`,
  DM_INBOX: `https://${DOMAIN}/i/api/1.1/dm/inbox_initial_state.json`,
  DM_CONVERSATION: (id: string | number): string => `https://${DOMAIN}/i/api/1.1/dm/conversation/${id}.json`,
  CONVERSATION_UPDATE_NAME: (id: string | number): string => `https://${DOMAIN}/i/api/1.1/dm/conversation/${id}/update_name.json`,
  NOTIFICATIONS_ALL: `https://${DOMAIN}/i/api/2/notifications/all.json`,
  NOTIFICATIONS_VERIFIED: `https://${DOMAIN}/i/api/2/notifications/verified.json`,
  NOTIFICATIONS_MENTIONS: `https://${DOMAIN}/i/api/2/notifications/mentions.json`,
  LIVE_PIPELINE_EVENTS: `https://api.${DOMAIN}/live_pipeline/events`,
  LIVE_PIPELINE_UPDATE_SUBSCRIPTIONS: `https://api.${DOMAIN}/1.1/live_pipeline/update_subscriptions`,
  USER_STATE: `https://api.${DOMAIN}/help-center/forms/api/prod/user_state.json`,
} as const;
